"""
testpilot init — One-command project setup.
Drops config.yaml + .vscode/tasks.json into any project.

Usage:
    python -m testpilot init
    python -m testpilot init --dir /path/to/your/project
"""
import os
import json
import shutil
import sys
from pathlib import Path


VSCODE_TASKS = {
    "version": "2.0.0",
    "tasks": [
        {
            "label": "TestPilot: Run All Tests",
            "type": "shell",
            "command": "python -m testpilot run",
            "group": {"kind": "test", "isDefault": True},
            "presentation": {"reveal": "always", "panel": "shared"},
            "problemMatcher": []
        },
        {
            "label": "TestPilot: Generate Tests (Changed Files)",
            "type": "shell",
            "command": "python -m testpilot generate --diff HEAD~1",
            "presentation": {"reveal": "always", "panel": "shared"},
            "problemMatcher": []
        },
        {
            "label": "TestPilot: Generate Tests (Current File)",
            "type": "shell",
            "command": "python -m testpilot generate --source ${file}",
            "presentation": {"reveal": "always", "panel": "shared"},
            "problemMatcher": []
        },
        {
            "label": "TestPilot: SOLR Validation",
            "type": "shell",
            "command": "python -m testpilot solr",
            "presentation": {"reveal": "always", "panel": "shared"},
            "problemMatcher": []
        },
        {
            "label": "TestPilot: React E2E",
            "type": "shell",
            "command": "python -m testpilot react",
            "presentation": {"reveal": "always", "panel": "shared"},
            "problemMatcher": []
        }
    ]
}

VSCODE_EXTENSIONS = {
    "recommendations": [
        "testpilot-ai.testpilot-ai",
        "ms-python.python",
        "ms-python.vscode-pylance"
    ]
}

DEFAULT_CONFIG = """\
# TestPilot AI — Configuration
# Generated by: python -m testpilot init
# Docs: https://github.com/saikatpatra-23/testpilot-ai

project:
  name: "{project_name}"

anthropic:
  api_key: ""              # REQUIRED: get from https://console.anthropic.com

backend:
  url: "http://localhost:8000"
  test_output_dir: "tests/ai_generated"
  source_dirs:
    - "src/"               # CHANGE: your Python source directory

siebel:
  enabled: false           # Set to true if you use Siebel CRM
  mode: "rest"             # "rest", "soap", or "both"
  rest:
    base_url: "https://siebel.yourorg.com/siebel/v1.0/data"
    username: ""           # Or env var: SIEBEL_USERNAME
    password: ""           # Or env var: SIEBEL_PASSWORD

solr:
  enabled: false           # Set to true if you use SOLR
  base_url: "http://localhost:8983/solr"
  collections:
    - name: "your_collection"
      required_fields: ["id", "title"]

frontend:
  enabled: false           # Set to true if you have a React/web frontend
  url: "http://localhost:3000"
  auth:
    email: ""
    password: ""

notifications:
  telegram:
    enabled: false
    bot_token: ""          # Create bot: talk to @BotFather on Telegram
    chat_id: ""            # Your chat ID or group ID
"""


def run_init(target_dir: str = None):
    target = Path(target_dir) if target_dir else Path.cwd()
    project_name = target.name

    print(f"\nTestPilot AI — Initializing in: {target}\n")

    # 1. config.yaml
    config_path = target / "config.yaml"
    if config_path.exists():
        print(f"  [skip] config.yaml already exists")
    else:
        config_path.write_text(DEFAULT_CONFIG.format(project_name=project_name), encoding="utf-8")
        print(f"  [created] config.yaml")

    # 2. .vscode/tasks.json
    vscode_dir = target / ".vscode"
    vscode_dir.mkdir(exist_ok=True)

    tasks_path = vscode_dir / "tasks.json"
    if tasks_path.exists():
        print(f"  [skip] .vscode/tasks.json already exists")
    else:
        tasks_path.write_text(json.dumps(VSCODE_TASKS, indent=2), encoding="utf-8")
        print(f"  [created] .vscode/tasks.json")

    # 3. .vscode/extensions.json
    ext_path = vscode_dir / "extensions.json"
    if not ext_path.exists():
        ext_path.write_text(json.dumps(VSCODE_EXTENSIONS, indent=2), encoding="utf-8")
        print(f"  [created] .vscode/extensions.json")

    # 4. tests/ directory
    tests_dir = target / "tests" / "ai_generated"
    tests_dir.mkdir(parents=True, exist_ok=True)
    gitkeep = tests_dir / ".gitkeep"
    if not gitkeep.exists():
        gitkeep.touch()
        print(f"  [created] tests/ai_generated/")

    # 5. Add to .gitignore
    gitignore_path = target / ".gitignore"
    gitignore_additions = ["config.yaml", "tests/ai_generated/"]
    if gitignore_path.exists():
        content = gitignore_path.read_text(encoding="utf-8")
        to_add = [line for line in gitignore_additions if line not in content]
        if to_add:
            with open(gitignore_path, "a", encoding="utf-8") as f:
                f.write("\n# TestPilot AI\n")
                for line in to_add:
                    f.write(f"{line}\n")
            print(f"  [updated] .gitignore (+{len(to_add)} entries)")
    else:
        gitignore_path.write_text("# TestPilot AI\nconfig.yaml\ntests/ai_generated/\n", encoding="utf-8")
        print(f"  [created] .gitignore")

    print(f"""
Done! Next steps:
  1. Open config.yaml and fill in:
       - anthropic.api_key  (https://console.anthropic.com)
       - backend.url        (your Python API)
       - siebel / solr      (enable + set URLs)

  2. Generate your first tests:
       python -m testpilot generate --source src/your_api.py

  3. Run tests:
       python -m testpilot run

  4. VS Code: Press Ctrl+Shift+P → "Tasks: Run Task" → "TestPilot: Run All Tests"
""")
